#ifndef ROBOT_SDK_CPP_PARAMETER_NRC_DEFINE_H
#define ROBOT_SDK_CPP_PARAMETER_NRC_DEFINE_H

using SOCKETFD = int;

enum Result {
    TIMEOUT = -6,
    EXCEPTION = -5,
    OPERATION_NOT_ALLOWED = -4,
    PARAM_ERR = -3,
    DISCONNECT = -2,
    RECEIVE_FAILED = -1,
    SUCCESS = 0
};

#endif // ROBOT_SDK_CPP_PARAMETER_NRC_DEFINE_H
